# This file was *autogenerated* from the file main.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)################################

# Matt Clay
# version 121017

################################

import sys # get command line arguments
# 1 = word, 2 = m, 3 = n, 4 = verbose

from scl import *

# parse input
if len(sys.argv) < _sage_const_4 :
    print 'Invalid input: not enough arguments'
    quit
    
g = sys.argv[_sage_const_1 ]
m = int(sys.argv[_sage_const_2 ])
n = int(sys.argv[_sage_const_3 ])
verbose = True if len(sys.argv)==_sage_const_5  else False

# compute scl
scl_g = scl(g,m,n,verbose)

if verbose == False: print scl_g
